package com.trs.template.dao.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.trs.template.dao.greendao.User;
import com.trs.template.dao.greendao.Beacon;

import com.trs.template.dao.greendao.UserDao;
import com.trs.template.dao.greendao.BeaconDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig beaconDaoConfig;

    private final UserDao userDao;
    private final BeaconDao beaconDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        beaconDaoConfig = daoConfigMap.get(BeaconDao.class).clone();
        beaconDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        beaconDao = new BeaconDao(beaconDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Beacon.class, beaconDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        beaconDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public BeaconDao getBeaconDao() {
        return beaconDao;
    }

}
